# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-08 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0001_initial_from_re2o'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipv6list',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipv6list', to='machines.Interface'),
        ),
        migrations.AddField(
            model_name='iptype',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.Extension'),
        ),
        migrations.AddField(
            model_name='iptype',
            name='ouverture_ports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.OuverturePortList'),
        ),
        migrations.AddField(
            model_name='iptype',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.Vlan'),
        ),
        migrations.AddField(
            model_name='iplist',
            name='ip_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.IpType'),
        ),
        migrations.AddField(
            model_name='interface',
            name='ipv4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.IpList'),
        ),
        migrations.AddField(
            model_name='interface',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine'),
        ),
        migrations.AddField(
            model_name='interface',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.MachineType'),
        ),
        migrations.AddField(
            model_name='interface',
            name='port_lists',
            field=models.ManyToManyField(blank=True, to='machines.OuverturePortList'),
        ),
        migrations.AddField(
            model_name='extension',
            name='origin',
            field=models.ForeignKey(blank=True, help_text='A record associated with the zone', null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.IpList'),
        ),
        migrations.AddField(
            model_name='extension',
            name='soa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.SOA'),
        ),
        migrations.AddField(
            model_name='domain',
            name='cname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_domain', to='machines.Domain'),
        ),
        migrations.AddField(
            model_name='domain',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.Extension'),
        ),
        migrations.AddField(
            model_name='domain',
            name='interface_parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Interface'),
        ),
        migrations.AddField(
            model_name='dname',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.Extension'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set([('name', 'extension')]),
        ),
    ]
