# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-09 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_from_re2o'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ban',
            options={'verbose_name': 'ban', 'verbose_name_plural': 'bans'},
        ),
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name': 'local email account', 'verbose_name_plural': 'local email accounts'},
        ),
        migrations.AlterModelOptions(
            name='listright',
            options={'verbose_name': 'group of rights', 'verbose_name_plural': 'groups of rights'},
        ),
        migrations.AlterModelOptions(
            name='listshell',
            options={'verbose_name': 'shell', 'verbose_name_plural': 'shells'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'school', 'verbose_name_plural': 'schools'},
        ),
        migrations.AlterModelOptions(
            name='serviceuser',
            options={'verbose_name': 'service user', 'verbose_name_plural': 'service users'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('change_user_password', 'Can change the password of a user'), ('change_user_state', 'Can edit the state of a user'), ('change_user_force', 'Can force the move'), ('change_user_shell', 'Can edit the shell of a user'), ('change_user_groups', 'Can edit the groups of rights of a user (critical permission)'), ('change_all_users', 'Can edit all users, including those with rights.')), 'verbose_name': 'user (member or club)', 'verbose_name_plural': 'users (members or clubs)'},
        ),
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name': 'whitelist (free of charge access)', 'verbose_name_plural': 'whitelists (free of charge access)'},
        ),
    ]
