# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-09 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20190408_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assooption',
            options={'verbose_name': 'organisation options'},
        ),
        migrations.AlterModelOptions(
            name='generaloption',
            options={'verbose_name': 'general options'},
        ),
        migrations.AlterModelOptions(
            name='homeoption',
            options={'verbose_name': 'homepage options'},
        ),
        migrations.AlterModelOptions(
            name='mailcontact',
            options={'verbose_name': 'contact email address', 'verbose_name_plural': 'contact email addresses'},
        ),
        migrations.AlterModelOptions(
            name='mailmessageoption',
            options={'verbose_name': 'email message options'},
        ),
        migrations.AlterModelOptions(
            name='optionalmachine',
            options={'verbose_name': 'machine options'},
        ),
        migrations.AlterModelOptions(
            name='optionaltopologie',
            options={'verbose_name': 'topology options'},
        ),
        migrations.AlterModelOptions(
            name='optionaluser',
            options={'verbose_name': 'user options'},
        ),
        migrations.AlterModelOptions(
            name='radiuskey',
            options={'verbose_name': 'RADIUS key', 'verbose_name_plural': 'RADIUS keys'},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'verbose_name': 'reminder', 'verbose_name_plural': 'reminders'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelOptions(
            name='switchmanagementcred',
            options={'verbose_name': 'switch management credentials'},
        ),
    ]
