# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-09 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0002_auto_20190408_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('buy_every_article', 'Can buy every article'),), 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='banque',
            options={'verbose_name': 'bank', 'verbose_name_plural': 'banks'},
        ),
        migrations.AlterModelOptions(
            name='costestimate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cotisation',
            options={'permissions': (('change_all_cotisation', 'Can edit the previous subscriptions'),), 'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='custominvoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'permissions': (('change_facture_control', 'Can edit the "controlled" state'), ('change_all_facture', 'Can edit all the previous invoices')), 'verbose_name': 'invoice', 'verbose_name_plural': 'invoices'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'permissions': (('use_every_payment', 'Can use every payment method'),), 'verbose_name': 'payment method', 'verbose_name_plural': 'payment methods'},
        ),
        migrations.AlterModelOptions(
            name='vente',
            options={'permissions': (('change_all_vente', 'Can edit all the previous purchases'),), 'verbose_name': 'purchase', 'verbose_name_plural': 'purchases'},
        ),
    ]
